export N_GPUS=8
export BASE_MODEL="deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
export CRITIC_MODEL="deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
export DATA_DIR=/home/robert/Documents/zyphra/TinyZero/data
export EXPERIMENT_NAME=eurus-qwen
export VLLM_ATTENTION_BACKEND=XFORMERS
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export ROLLOUT_TP_SIZE=1

# export WANDB_API_KEY=""
# export HF_TOKEN=""
# export HF_HUB_ENABLE_HF_TRANSFER=1
# actor_rollout_ref.actor.ulysses_sequence_parallel_size=2 \
# actor_rollout_ref.ref.ulysses_sequence_parallel_size=2 \
# critic.ulysses_sequence_parallel_size=2 \

python3 -m verl.trainer.main_ppo \
data.train_files=$DATA_DIR/train.parquet \
data.val_files=$DATA_DIR/test.parquet \
data.train_batch_size=256 \
data.val_batch_size=1024 \
data.max_prompt_length=1024 \
data.max_response_length=32768 \
actor_rollout_ref.actor.ulysses_sequence_parallel_size=8 \
actor_rollout_ref.ref.ulysses_sequence_parallel_size=8 \
critic.ulysses_sequence_parallel_size=8 \
actor_rollout_ref.actor.fsdp_config.param_offload=True \
actor_rollout_ref.actor.fsdp_config.grad_offload=True \
actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
actor_rollout_ref.ref.fsdp_config.param_offload=True \
actor_rollout_ref.model.use_remove_padding=True \
actor_rollout_ref.actor.use_dynamic_bsz=True \
actor_rollout_ref.actor.ppo_max_token_len_per_gpu=70000 \
actor_rollout_ref.model.path=$BASE_MODEL \
actor_rollout_ref.actor.optim.lr=1e-6 \
actor_rollout_ref.actor.ppo_mini_batch_size=128 \
actor_rollout_ref.actor.ppo_micro_batch_size=4 \
++actor_rollout_ref.rollout.use_dynamic_bsz=True \
++actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=70000 \
actor_rollout_ref.rollout.log_prob_micro_batch_size=8 \
actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP_SIZE \
actor_rollout_ref.rollout.gpu_memory_utilization=0.85 \
++actor_rollout_ref.ref.use_dynamic_bsz=True \
++actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=70000 \
actor_rollout_ref.ref.log_prob_micro_batch_size=8 \
critic.model.use_remove_padding=True \
critic.model.enable_gradient_checkpointing=True \
++critic.use_dynamic_bsz=True \
++critic.ppo_max_token_len_per_gpu=140000 \
critic.optim.lr=1e-5 \
critic.model.path=$CRITIC_MODEL \
critic.ppo_micro_batch_size=8 \
algorithm.kl_ctrl.kl_coef=0.001 \
trainer.logger=['wandb'] \
+trainer.val_before_train=False \
trainer.default_hdfs_dir=null \
trainer.n_gpus_per_node=$N_GPUS \
trainer.nnodes=1 \
trainer.save_freq=16 \
trainer.test_freq=64 \
trainer.project_name=TinyZero \
trainer.experiment_name=$EXPERIMENT_NAME \
trainer.total_epochs=15 2>&1 | tee verl_demo.log